name: Bonjour
on:
  - push
jobs:
  prefab:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/dduportal/esgi-gitpod
      options: --user=root
    steps:
      - uses: actions/checkout@v4 
      - run: npm clean-install && npm run lint